sudo: required

services:
  - docker

language: scala

scala:
   - 2.11.7

jdk:
  - oraclejdk8

before_install:
  - docker pull springcloud/configserver
  - docker run -d -p 127.0.0.1:8888:8888 springcloud/configserver
  - docker ps -a
